name: Vavoo M3U Otomatik Guncelleyici

on:
  schedule:
    # Her gün gece 03:00'te (UTC) otomatik çalışır
    - cron: '0 3 * * *'
  workflow_dispatch: # Manuel olarak "Actions" sekmesinden de başlatabilirsin

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dosyayı depoya geri yazabilmek için gerekli

    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Bağımlılıkları Yükle
        run: |
          pip install requests

      - name: Scripti Çalıştır
        run: |
          python vavoo_hazir.py --full-m3u

      - name: Değişiklikleri Kaydet ve Gönder
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add vavoo_full.m3u
          git commit -m "Güncel Vavoo Listesi: $(date +'%Y-%m-%d %H:%M')" || echo "Değişiklik yok."
          git push
          
